### ISSUE TITLE
Еrror when downloading from http://opensource.lge.com

### ISSUE THREAD

**Issue by Voronoff-lg** [LGE-OSS/ko#3]
Hello. 
Recently I have been unable to download files from http://opensource.lge.com due to a web server error. Here is an example http://opensource.lge.com/product/list?page=&ctgr=&subCtgr=&keyword=55b4rla&schType=. 
If you click download webOS 24 K_1.0_2303_2.tar.gz or webOS 24 K_1.0_3.tar.gz, then
after the download starts, a few seconds later (about 100-200 MB downloaded) a server error is displayed and the connection is lost. I used Chrome and FireFox. Could you check what's wrong or pass this message on to colleagues who support the site?
Thanks in advance.

**Comment by soimkim** [comment]
@Voronoff-lg , 
I clicked the icon below in Chrome and downloaded it normally.
![image](https://github.com/user-attachments/assets/b0699bd8-e989-4aca-bb23-864c00dc4dfa)

However, the file size is large, so it may take a long time depending on the network environment.
In my case, it took 20 minutes.
Please try downloading it again.

**Comment by Voronoff-lg** [comment]
Hello, 
Thanks for answer.

Part of Chrome downloads history from 22 Dec to 23 Dec:

webOS 24 K_1.0_2.tar.gz Failed - Unknown server error. Please try again, or contact the server administrator.

webOS 24 K_2.0_2.tar.gz Failed - Unknown server error. Please try again, or contact the server administrator.

webOS 24 K_1.0_2303_3.tar.gz Failed - Unknown server error. Please try again, or contact the server administrator.

webOS 24 K_1.0_2.tar.gz Failed - Unknown server error. Please try again, or contact the server administrator.

webOS 24 K_1.0_2.tar.gz Failed - Unknown server error. Please try again, or contact the server administrator.

webOS 24 K_1.0_3.tar.gz Failed - Unknown server error. Please try again, or contact the server administrator.

webOS 24 K_1.0_2303_2.tar.gz Failed - Unknown server error. Please try again, or contact the server administrator.

webOS 24 K_1.0_3.tar.gz Failed - Unknown server error. Please try again, or contact the server administrator.

webOS 24 K_1.0_2.tar.gz Failed - Unknown server error. Please try again, or contact the server administrator.

webOS 24 K_1.0_2.tar.gz Failed - Unknown server error. Please try again, or contact the server administrator.

webOS 24 K_1.0_2303_3.tar.gz Failed - Unknown server error. Please try again, or contact the server administrator.

![FireShot Capture 014 - Download history - downloads](https://github.com/user-attachments/assets/23812164-d8cd-427f-b77b-502045708a1c)

p.s. today is ok, error on server is fixed, can download

**Comment by Min-Kyungsun** [comment]
I'm glad to hear that the download was successful. If you have any further inquiries, please feel free to contact me anytime. Thank you!
Merry Christmas🎅🏻
